import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { CalendarDays, Droplets, Package } from "lucide-react";
import ManagerSidebar from "../../components/ManagerSidebar";
import { api } from "../../lib/api";
const today = () => new Date().toISOString().slice(0, 10);
export default function ManagerDashboard() { const navigate = useNavigate(); const [orders, setOrders] = useState([]); const [error, setError] = useState(""); useEffect(() => { api("/party-orders").then((r) => setOrders(r.data || [])).catch((e) => setError(e.message)); }, []); const calculate = (filter) => { const rows = orders.filter(filter); return { count: rows.length, jars: rows.reduce((sum, item) => sum + Number(item.total_jars || 0), 0), water: rows.reduce((sum, item) => sum + Number(item.water_liters || 0), 0) }; }; const pending = calculate((o) => o.status !== "completed" && o.status !== "delivered" && o.event_date <= today()); const upcoming = calculate((o) => o.status !== "completed" && o.status !== "delivered" && o.event_date > today()); return <div className="flex min-h-screen bg-slate-100"><ManagerSidebar /><main className="w-full p-4 pb-24 md:ml-60 md:p-6"><p className="text-sm font-semibold text-blue-700">Manager dashboard</p><h1 className="mb-5 text-2xl font-bold">Party orders</h1>{error && <p className="mb-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<OrderCard title="Today's pending orders" data={pending} color="blue" onClick={() => navigate("/manager/party-orders?scope=today")} /><OrderCard title="Upcoming orders" data={upcoming} color="cyan" onClick={() => navigate("/manager/party-orders?scope=upcoming")} /></main></div>; }
function OrderCard({ title, data, color, onClick }) { return <button onClick={onClick} className={`mb-4 w-full rounded-3xl p-5 text-left text-white shadow transition hover:scale-[1.01] ${color === "blue" ? "bg-blue-600" : "bg-cyan-600"}`}><div className="mb-4 flex items-center justify-between"><span className="text-lg font-bold">{title}</span><CalendarDays /></div><div className="grid grid-cols-3 gap-2"><Stat icon={<Package size={17} />} label="Orders" value={data.count} /><Stat icon={<Package size={17} />} label="Jars" value={data.jars} /><Stat icon={<Droplets size={17} />} label="Water (L)" value={data.water} /></div><p className="mt-4 text-sm font-semibold underline">View pending & completed orders</p></button>; }
function Stat({ icon, label, value }) { return <div className="rounded-2xl bg-white/15 p-3"><span className="flex items-center gap-1 text-xs opacity-90">{icon}{label}</span><strong className="mt-1 block text-2xl">{value}</strong></div>; }
